# To use:
#   $ conda env create -f final_project_wbs.yml
#   $ conda activate fpwbs
name: fpwbs
dependencies:
  - python=3.9
  - pip
  - pip:
    - tensorflow
    - opencv
    - sklearn
    - tensorflow
    - pandas
    - numpy
    - scikit-image
    - matplotlib
    - jupyter
    - tqdm
    - Pillow
    - ipykernel


